# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  pre_release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install and fix
        run: |
          npm install
          npx eslint --fix .

      - name: Build Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Archive DMG
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v2
        with:
          name: ambeeance-prerelease-${{ github.sha }}.dmg
          path: dist/ambeeance*.dmg

      - name: Archive EXE
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v2
        with:
          name: ambeeance-prerelease-${{ github.sha }}.exe
          path: dist/ambeeance*.exe

      - name: Archive DEB
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          name: ambeeance-prerelease-${{ github.sha }}.zip
          path: |
            dist/ambeeance*.AppImage
            dist/ambeeance*.snap
